// <auto-generated />
namespace Lecturers.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addclass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addclass));
        
        string IMigrationMetadata.Id
        {
            get { return "202305150705300_add-class"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
